"""nevermore

Revision ID: 8ecc61c53b98
Revises:
Create Date: 2023-03-19 17:31:46.169916

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8ecc61c53b98"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application",
        sa.Column("phone", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_application_email"), "application", ["email"], unique=False
    )
    op.create_index(op.f("ix_application_id"), "application", ["id"], unique=False)
    op.create_index(
        op.f("ix_application_phone"), "application", ["phone"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_application_phone"), table_name="application")
    op.drop_index(op.f("ix_application_id"), table_name="application")
    op.drop_index(op.f("ix_application_email"), table_name="application")
    op.drop_table("application")
    # ### end Alembic commands ###
