"""nevers

Revision ID: f0f86497b115
Revises: 03d6e17a9214
Create Date: 2023-03-20 17:23:07.970340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f0f86497b115"
down_revision = "03d6e17a9214"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
